server.port=9100
spring.datasource.url=jdbc:postgresql://localhost:5432/prova

spring.datasource.username=prova
spring.datasource.password=prova
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
